/* eslint-disable*/

import { Inter } from "next/font/google";
import "./globals-css/globals.css";
import Navbar from "@/custom_components/Navbar/page";
import Footer from "@/custom_components/footer/Footer";
import ContactUsCard from "@/custom_components/contactUsCard/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-yellow-50 `}>
        <Navbar></Navbar>
        {children}
        <ContactUsCard></ContactUsCard>
        <Footer></Footer>{" "}
      </body>
    </html>
  );
}
