/* eslint-disable*/
"use client"

import { useEffect } from "react";
import { Inter } from "next/font/google";
import "./globals-css/globals.css";
import Navbar from "@/custom_components/Navbar/page";
import Footer from "@/custom_components/footer/Footer";
import ContactUsCard from "@/custom_components/contactUsCard/page";
import Script from 'next/script';




const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  useEffect(() => {
    // Render the script on the client-side
    if (typeof window !== 'undefined') {
      document.body.appendChild(
        document.createElement('script')
      ).src = 'https://checkout.razorpay.com/v1/checkout.js';
    }
  }, []);
  return (
    <html lang="en" className="scroll-smooth" >
      <body className={`${inter.className} bg-yellow-50 `}>
        <Navbar></Navbar>
        {children}
        <ContactUsCard></ContactUsCard>
        <Footer></Footer>{" "}
      </body>
    </html>
  );
}
{/* <script src="https://checkout.razorpay.com/v1/checkout.js"></script> */ }
// 


